### ISSUE TITLE
second `npm install` gives error (unstable branch)

### ISSUE THREAD

**Issue by canbax** [iVis-at-Bilkent/cytoscape.js-fcose#12]
First `npm install` works fine. 
When I run it for the second time. It changes **package-lock.json** file. Like below. (when I revert changes, `npm install` runs fine)
![image](https://user-images.githubusercontent.com/8426741/68272047-989ebb80-0073-11ea-9517-f7e5005d3e4a.png)

It gives below error when I run `npm install` second time. 

PS D:\...\..> npm i
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "cose-base@1.0.1": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2019-11-06T05_59_08_270Z-debug.log

When I check the log files mentioned in the error I see

20 verbose stack Error: Invalid tag name "cose-base@1.0.1": Tags may not have any characters that encodeURIComponent encodes.
20 verbose stack     at invalidTagName (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:91:15)
20 verbose stack     at fromRegistry (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:296:13)
20 verbose stack     at Function.resolve (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:81:12)
20 verbose stack     at childDependencySpecifier (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:102:14)
20 verbose stack     at addDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:568:19)
20 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:516:5
20 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
20 verbose stack     at Array.forEach (<anonymous>)
20 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
20 verbose stack     at Array.forEach (<anonymous>)
20 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
20 verbose stack     at loadDeps (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:514:3)
20 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
20 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
20 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
20 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\and-finish-tracker.js:8:8
21 verbose cwd D:\yusuf\visuall
22 verbose Windows_NT 10.0.17134
23 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
24 verbose node v12.13.0
25 verbose npm  v6.12.0
26 error code EINVALIDTAGNAME
27 error Invalid tag name "cose-base@1.0.1": Tags may not have any characters that encodeURIComponent encodes.
28 verbose exit [ 1, true ]

**Comment by hasanbalci** [comment]
@canbax I think you don't get the latest unstable of the fcose. The latest commit SHA in unstable is 0b47401dfb5a8a533f0a1d3554d4905a9c211135, but in the image you sent it seems the last commit you get is e103493faa0129cff0de419f70ec950be6f4f3ba which a relatively old commit. Can you please use `npm update` to update the fcose to the latest unstable and then try again?

**Comment by canbax** [comment]
thank you. `npm update` changed the commit.

note: `npm update` updates all of the dependencies.
