### ISSUE TITLE
Position ignored by Cytoscape

### ISSUE THREAD

**Issue by pmuno007** [iVis-at-Bilkent/cytoscape.js-fcose#14]
I currently have a graph with 3000 nodes and 15000 edges. Loading of this graph takes about 1 minute and 30 seconds. I tried pre-assigning positions to the nodes to reduce loading times, but these seem to be ignored on load, and cytoscape recalculates the positions, which I imagine happens due to the clustering. Is there anyway to pre-assign positions to the graph data to help reduce loading times?

**Comment by hasanbalci** [comment]
@pmuno007 I didn't understand how this is related with fcose. If you're trying to apply a layout after you add graph elements to cytoscape, cytoscape uses [grid](https://js.cytoscape.org/#layouts/grid) layout as default if you don't specify a layout. If you have position information for your nodes and want to use those positions on load, then you need to use [preset](https://js.cytoscape.org/#layouts/preset) layout. If that 1 minute and 30 seconds is when you apply fcose, I can suggest you use fcose with quality option "draft" for a faster but relatively poor quality layout.
