### ISSUE TITLE
Tree reduction during non-incremental layout

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-fcose#18]
Currently non-incremental layout of fcose calls incremental layout of the cose algorithm, which doesn't reduce trees, and hence takes longer. There is not much of a reason not to reduce the trees during non-incremental layout of fcose though. So, if we can implement a non-exposed flag named to cose (cose-bilkent) to force tree reduction (even during incremental cose) and set it to true for non-incremental cose, that'd be great.

**Comment by hasanbalci** [comment]
With this commit https://github.com/iVis-at-Bilkent/cytoscape.js-fcose/commit/d2d3d81535e95b932bd17da5a2c3fe7774a280d8, tree reduction is now applied during non-incremental layout.
