### ISSUE TITLE
Update demos with non-uniform node dimensions

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-fcose#2]
In order to show off the capability of this algorithm to support non-uniform node dimensions, we should change the demo graphs to contain nodes of varying sizes.

**Comment by hasanbalci** [comment]
With [this commit](https://github.com/iVis-at-Bilkent/cytoscape.js-fcose/commit/fa61f726941c929b82ea7eedd26a02c9bcb1cc09), I assigned three different sizes (30, 50, 70) to nodes randomly.
