### ISSUE TITLE
Cannot read property 'descendants' of undefined

### ISSUE THREAD

**Issue by cskyer** [iVis-at-Bilkent/cytoscape.js-fcose#25]
Cannot read property 'descendants' of undefined

**Comment by hasanbalci** [comment]
@qq2575896094 Can you please give more detail about the issue? In which case did you get the error? It would be better if you provide a JSFiddle or JSBin demo to reproduce this issue. Thanks!

**Comment by hasanbalci** [comment]
I now remembered that this bug occurs in the current release when there is no nodes in the graph and one tries to apply layout. This bug is solved in the unstable branch and will be available with the next release. So, I'm closing the issue.
