### ISSUE TITLE
Constraint demo improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-fcose#26]
- [x] 1. "Cose" -> "CoSE"
- [x] 2. "Add selected to ver./hor. alignment": let's change these as label/text ("Selected Nodes Vertically/Horizontally") followed by an "Add" button
- [x] 3. Add some minimal padding around the three sections (File | Layout | Constraints) so the three sections are nicely identifiable.
- [x] 4. For import/export constraints, let's have a label/text "Constraints" before buttons followed by buttons "Import" and "Export". The buttons should have the same style as others (e.g. "Add"); text, background and border colors
- [x] 5. For adding fixed constraints, why not put the node label and coordinate info & add button all in one line.
- [x] 6. Make the background of the dropdown box when dropped (currently it is dark green?) black (keep white text).
- [x] 7. Make the background of the dropdown box when not dropped white (same as the file list), not cyan.
- [x] 8. Other demos should be modified accordingly as well.

**Comment by hasanbalci** [comment]
@ugurdogrusoz I updated all three demo files. Can you please review them?
