### ISSUE TITLE
the compound style could be a circle ?

### ISSUE THREAD

**Issue by ghost** [iVis-at-Bilkent/cytoscape.js-fcose#29]
I want to build this https://nivo.rocks/bubble bubble style( circle style), but the compound style is rectangle.

Is there a way set a circle style ? 

Thank you !

**Comment by hasanbalci** [comment]
@steveyang331 Hi, unfortunately Cytoscape.js supports only rectangle, round-rectangle, cut-rectangle and barrel shapes for compound nodes as stated [here](https://js.cytoscape.org/#style/node-body).

**Comment by steveyang331** [comment]
Oh there had a reply :
https://github.com/iVis-at-Bilkent/cytoscape.js-fcose/issues/29#issuecomment-759373859

**Comment by ghost** [comment]
@hasanbalci Thank you for sharing !

May I request add circle style feature ?

**Comment by ghost** [comment]
I found G6 support  https://antv-g6.gitee.io/en/examples/item/defaultCombos

**Comment by hasanbalci** [comment]
@steveyang331 fCoSE is just a layout extension for Cytoscape.js library, please directly contact with [Cytoscape.js](https://github.com/cytoscape/cytoscape.js) for such feature requests. Thanks!
