### ISSUE TITLE
bad layout with expand collapse

### ISSUE THREAD

**Issue by canbax** [iVis-at-Bilkent/cytoscape.js-fcose#34]
When I use fcose inside [expand-collapse extension, ](https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse) I see very bad layouts on expand.

Below is a very small video showing what happens on [Visuall](http://visuall.herokuapp.com/). You can reproduce the video by loading [visuall.txt](https://github.com/iVis-at-Bilkent/cytoscape.js-fcose/files/6161815/visuall.txt) inside [Visuall](http://visuall.herokuapp.com/). (File>Load)

https://user-images.githubusercontent.com/8426741/111583972-45438e00-87ce-11eb-8809-f4f52acd06a5.mp4

Here is also a [JSBIN](https://jsbin.com/lugetup/edit?html,css,js,console,output)

You can try collapsing and then expanding an inner compound node.

**Comment by hasanbalci** [comment]
It seems that the source of the buggy behavior is not the layout algorithm but the expand-collapse extension, so I fixed the issue there.

**Comment by ugurdogrusoz** [comment]
@canbax Can you please confirm this fix?

**Comment by canbax** [comment]
It seems better now. I tested on http://visuall.herokuapp.com/
