### ISSUE TITLE
Allow apsectRatio paramater for packComponents

### ISSUE THREAD

**Issue by EliotRagueneau** [iVis-at-Bilkent/cytoscape.js-fcose#39]
Hi, 
We, at IntAct, are really interested in the packing component option as it has always been an issue in Cytoscape. 
Currently, the aspectRatio of cytoscape.js-layout-utilities is by default 1, if I analysed correctly.
![Screenshot 2021-05-18 at 11 05 49](https://user-images.githubusercontent.com/42945601/118633110-07141c00-b7c9-11eb-9b97-9b8d3eb0d7ee.png)

However, it would be really nice if by default the actual aspectRatio could be the one of the canvas, this way, even on large horizontal screens, most of the space would be used to have a better display.

A simpler solution though would be to include the aspectRatio among the different layout options, so that devs can fill it with the aspect ratio of their canvas, if they need to.

Maybe it's already available on a certain branch though, in which case I'm sorry to have created an issue for that.

**Comment by hasanbalci** [comment]
@EliotRagueneau fCoSE actually provides component packing functionality via [cytoscape-layout-utilites](https://github.com/iVis-at-Bilkent/cytoscape.js-layout-utilities) extension and this extension has some packing-related options such as `desiredAspectRatio` and `componentSpacing`. So you can adjust the aspect ratio according to your canvas size as in fCoSE [demo](https://ivis-at-bilkent.github.io/cytoscape.js-fcose/demo/demo.html) and the corresponding code is [here](https://github.com/iVis-at-Bilkent/cytoscape.js-fcose/blob/908eae19324f284b6f044e27d07ed77811588055/demo/demo.html#L148).

**Comment by EliotRagueneau** [comment]
Oh wow that's really nice, and fits perfectly our needs, thank you very much.
I thought it needed to be a layout parameter, but it makes total sense to do it this way.
