### ISSUE TITLE
[BUG] Crash when connecting between nodes within a group

### ISSUE THREAD

**Issue by Ghost---Shadow** [iVis-at-Bilkent/cytoscape.js-fcose#5]
Minimum element array which causes the crash

```javascript
[
  { data: { id: 'n0' } },
  { data: { id: 'n1', parent: 'n0' } },
  { data: { id: 'n2', parent: 'n0' } },
  { data: { id: 'e1', source: 'n1', target: 'n2' } },
];
```
![error](https://i.imgur.com/fC23Gnk.png)

Surrounding the block with a try catch works

![expected](https://imgur.com/LlnYr7o.png)

This is a `fcose` related issue as `cytoscape-cose-bilkent` does not crash.

I am also using `react-cytoscapejs` as the React wrapper for cytoscape

**Comment by hasanbalci** [comment]
@Ghost---Shadow  The bug should be fixed in the unstable branch. Can you test and verify?

**Comment by Ghost---Shadow** [comment]
@hasanbalci The crash is fixed. You can close the isssue.
