### ISSUE TITLE
Could not find a declaration file for module 'cytoscape-fcose'

### ISSUE THREAD

**Issue by jonng1000** [iVis-at-Bilkent/cytoscape.js-fcose#51]
Hi, I am using react-cytoscapejs in my code, and when I import fcose as per the instructions here:
`import Cytoscape from 'cytoscape';
import fcose from 'cytoscape-fcose';`

I get this error:
`module "C:/Users/weixiong001/Documents/golabel/node_modules/cytoscape-fcose/cytoscape-fcose"
Could not find a declaration file for module 'cytoscape-fcose'. 'C:/Users/weixiong001/Documents/golabel/node_modules/cytoscape-fcose/cytoscape-fcose.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/cytoscape-fcose` if it exists or add a new declaration (.d.ts) file containing `declare module 'cytoscape-fcose';`ts(7016)`

May I know how do I fix this issue please? Or can I safely ignore it?

Thank you
Jonathan

**Comment by hasanbalci** [comment]
I suppose it's related with your TypeScript settings. You can check [this](https://stackoverflow.com/questions/61258923/how-to-solve-the-could-not-find-a-declaration-file-for-module-error-using-my-o) and [this](https://stackoverflow.com/questions/43064221/typescript-ts7006-parameter-xxx-implicitly-has-an-any-type?rq=1) pages in stackoverflow for possible solutions.

**Comment by jonng1000** [comment]
Dear Hasan,

Thanks for your quick reply. I've read those pages but am still lost. Do you if its possible for me to get step by step instructions to set the types correctly? I understand I have to do that but am not sure how. Very sorry for the trouble. I am new to javascript 
and come from a python background. Would uninstalling and reinstalling this module help?

Many thanks
Jonathan

**Comment by hasanbalci** [comment]
Unfortunately, I'm not very experienced with TypeScript either. Maybe, you can also use stackoverflow for a detailed answer.
