### ISSUE TITLE
How to use Cytoscape fcose in Vue. Are there any examples

### ISSUE THREAD

**Issue by zx2022x** [iVis-at-Bilkent/cytoscape.js-fcose#58]
help,my country do not this case

**Comment by hasanbalci** [comment]
@zx2022x I'm not experienced with Vue.js, but vanilla JavaScript can be used in Vue.js, so the Usage Instructions in the Readme should be valid. You may ask this question in stackoverflow to reach a wider community which probably includes developers using Vue.js with Cytoscape.js extensions.

**Comment by zx2022x** [comment]
> @zx2022x我对 Vue.js 没有经验，但是在 Vue.js 中可以使用 vanilla JavaScript，因此自述文件中的使用说明应该是有效的。您可以在 stackoverflow 中提出这个问题，以接触更广泛的社区，其中可能包括使用 Vue.js 和 Cytoscape.js 扩展的开发人员。
非常感谢您的的回答，我解决了这个问题
