### ISSUE TITLE
Compound node alignment

### ISSUE THREAD

**Issue by kaushikosu** [iVis-at-Bilkent/cytoscape.js-fcose#59]
I am trying to add compound nodes to the alignment property of the layout and it does not work.

**Comment by ugurdogrusoz** [comment]
This layout supports constraints only on simple nodes as stated in the [README](https://github.com/iVis-at-Bilkent/cytoscape.js-fcose#documentation).

**Comment by kaushikosu** [comment]
can this be an enhancement request ?
