### ISSUE TITLE
Pack disconnected graph components using new utility

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-fcose#6]
Let's pack the disconnected graph components using the [new utility](https://github.com/iVis-at-Bilkent/cytoscape.js-layout-utilities) as suggested in its README. We should add a new option to this layout though named *packComponents*, which is true by default to control the use of this facility.

**Comment by hasanbalci** [comment]
I added this functionality to the layout and updated compound demo to check this feature.

**Comment by ugurdogrusoz** [comment]
Can we set desired aspect ratio to be 16:9 or to be the actual value of the Cytoscape.js canvas if possible?
Can we also increase the component spacing to leave more room around components.
