### ISSUE TITLE
Empty compounds mess up layout

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-fcose#60]
Looks like when there are empty compound nodes in the graph, these compound nodes are not taken into account, messing up the layout.

**Comment by hasanbalci** [comment]
The problem was because of the hidden nodes in the compounds which make them empty. Now, user should give all elements to the layout including the hidden ones, but the layout will not consider hidden ones during the layout (actually spectral part considers but cose part doesn't consider).

**Comment by ugurdogrusoz** [comment]
@hasanbalci thanks I confirm the fix with the extension demo.
@osamazafar980 can you please check this in IAM application as well (please note the comment above for its usage).

**Comment by osamazafar980** [comment]
I am still seeing some issues. The empty compound nodes are creating massive gaps which then gets overlapped by other compounds

**Comment by ugurdogrusoz** [comment]
@osamazafar980 Please close this if you tested it
