### ISSUE TITLE
Overlapping labels for unconnected nodes

### ISSUE THREAD

**Issue by burner1024** [iVis-at-Bilkent/cytoscape.js-fcose#62]
Even `nodeDimensionsIncludeLabels: true` doesn't help:
![Captura desde 2023-01-23 04-52-35](https://user-images.githubusercontent.com/1279852/213942353-d979fd5c-4012-4894-a411-7df4c82b7185.png)

**Comment by burner1024** [comment]
And it appears that `fixedNodeConstraint` and `alignmentConstraint` also don't work for orphan nodes.

**Comment by ugurdogrusoz** [comment]
In this example, does not look like `nodeDimensionsIncludeLabels` is true but in any case, with such a dense graph node overlaps will be unavoidable. The only thing that might help is increasing the `idealEdgeLength` option.

**Comment by burner1024** [comment]
I'm talking about the right side, all the free nodes. I don't think edge length would have any effect on that anyway?

**Comment by hasanbalci** [comment]
@burner1024 Please see [this example](https://jsbin.com/vuvobakuri/edit?js,output) where `nodeDimensionsIncludeLabels` option works.

**Comment by burner1024** [comment]
It appears so. I will re-check, thank you.

**Comment by burner1024** [comment]
My bad, I passed layout option to original cytoscape invocation, then ran it separately.
```typescript
options = {...}
const cy = cytoscape({
        layout: {
            name: "fcose",
        },
...
};
cy.layout(options).run()
```
Shouldn't have passed layout arg to cytoscape. Looks like it ran the algorithm with default options.

Thanks again.
