### ISSUE TITLE
Is there a way to define <= relativePlacementConstraint ?

### ISSUE THREAD

**Issue by dumbPy** [iVis-at-Bilkent/cytoscape.js-fcose#65]
I would like to limit the total width (or height) of a graph and hence would like to define less-than-or-equal (<=) relative placement constraints where the distance between 2 points in a given dimension is not more than the defined value (as opposed to be above the given gap value).

**Comment by ugurdogrusoz** [comment]
@dumbPy fCoSE does not support such a constraint at the moment. may be you can use other constraints to sort of emulate this but I am not sure how.

**Comment by dumbPy** [comment]
Thanks a lot @ugurdogrusoz . After quite a bit of experimentation, realised that I can add virtual nodes L0 and R0 and fix them at `x=0` and `x=pageWidth` respectively and add `relativePlacementConstraint` to keep all nodes right of L0 and left of R0. Works like a charm.
