### ISSUE TITLE
Is there a more pure component that can run independently without relying on cytoscape?

### ISSUE THREAD

**Issue by wangxiaofeid** [iVis-at-Bilkent/cytoscape.js-fcose#68]

**Comment by hasanbalci** [comment]
Hi, there is [this component](https://github.com/iVis-at-Bilkent/cose-base). It is used by fCoSE but it is missing the part that makes fCoSE a faster version of CoSE-Bilkent layout (That part has been implemented with cytoscape for now.). However, CoSE-Bilkent layout uses this pure, cytoscape-independent component.
